### ISSUE TITLE
Article 1 : problème en ligne 

### ISSUE THREAD

**Issue by GuyliannEngels** [armelyonkeu/armel-yonkeu-blog#1]
@armelyonkeu, 

J'ai modifié to article 1 afin de corriger les problemes. 

Prends exemple sur cet article pour les suivants

**Comment by armelyonkeu** [comment]
Merci beaucoup M je le ferais

Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone
Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________
