### ISSUE TITLE
Erreur lors d'un PULL

### ISSUE THREAD

**Issue by GuyliannEngels** [armelyonkeu/armel-yonkeu-blog#3]
Salut @armelyonkeu ,

Lors d'un problème lié à un projet, je ne réponds que par ISSUE.

Voici ton mail : Difficultés  après avoir fait un pull

Bonjour M, j'ai essayer de faire un pull des modifications que vous avez faites sur mon blog il a un message qui m'ai apparu

![20191025_110026](https://user-images.githubusercontent.com/33956170/67560331-f3065680-f71a-11e9-8f18-47c1a66464d4.jpg)

En lisant le message j'ai pensé qu'on me demandais de faire un comit avant de faire le pull ce que j'ai fait après quoi il y'a trois nouveaux documents que ce sont ajoutés. Je n'arrive pas à visualiser ces modifications quand je cherche dans mes dossiers je vois rien

![20191025_111524](https://user-images.githubusercontent.com/33956170/67561039-665c9800-f71c-11e9-99a2-d9f4d4402919.jpg)

Comment faire pour visualiser cela dans ma zone d'édition???

Je te propose des solutions. Quand tu as ta solution, tu fermes l'issue

**Comment by GuyliannEngels** [comment]
Tu dois fermer tes documents, faire un commit et puis ton PULL

**Comment by GuyliannEngels** [comment]
J'ai répondu un peu vote à ton mail. 
Les fichiers que tu pointes sont des fichiers que tu ne dois pas éditer. Ils configurent ton site

**Comment by armelyonkeu** [comment]
d accord je ferme mes documents

**Comment by armelyonkeu** [comment]
j ai fait le pull mais je vois toujours pas

**Comment by GuyliannEngels** [comment]
Tu arrives à faire ton PULL ? si oui fait un PUSH ensuite

**Comment by armelyonkeu** [comment]
ok

**Comment by armelyonkeu** [comment]
voila le message que j ai eu apres avoir fait le push

>>> git push origin HEAD:refs/heads/master
To https://github.com/armelyonkeu/armel-yonkeu-blog.git
   f435051..18a9261  HEAD -> master

**Comment by GuyliannEngels** [comment]
cela signifie que tu as bien fait push

**Comment by armelyonkeu** [comment]
les modifications s inserent directement dans mon travail initial?

**Comment by GuyliannEngels** [comment]
quand je regarde ton dépot, tu as bien fait ton PUSH 

Par contre dans ton article, tu as laissé des conflits que tu dois gérer 

![Capture d’écran 2019-10-25 à 12 09 24](https://user-images.githubusercontent.com/33956170/67563141-69598780-f720-11e9-957f-467fb86a7151.png)

**Comment by armelyonkeu** [comment]
comment je fait?? ou lire pour savoir comment gerer les conflits

**Comment by armelyonkeu** [comment]
bonjour M, j'ai pu resoudre les conflits merci beaucoup

**Comment by GuyliannEngels** [comment]
Bravo @armelyonkeu :)
