### ISSUE TITLE
problèmes avec le blog

### ISSUE THREAD

**Issue by armelyonkeu** [armelyonkeu/armel-yonkeu-blog#4]
Bonsoir M, lorsque j'utlise l'url de mon blog je ne vois pas l'article que j'y ajouté est ce normal?

**Comment by armelyonkeu** [comment]
@GuyliannEngels

**Comment by armelyonkeu** [comment]
Bonsoir M, lorsque j'utlise l'url de mon blog je ne vois pas l'article que j'y ajouté est ce normal?

**Comment by GuyliannEngels** [comment]
Salut @armelyonkeu ,

Je n'arrive pas à compiler (*knit*) ton article 1. Il me manque la photo pour cela. 
peux tu ajouter la photo manquante dans ton projet et réaliser un commit puis un push

![armel_blog1](https://user-images.githubusercontent.com/33956170/67923778-22034900-fbaf-11e9-9ced-9300c39dda40.png)

**Comment by armelyonkeu** [comment]
d'accord M je m'y met à
________________________________
De : Guyliann Engels <notifications@github.com>
Envoyé : jeudi 31 octobre 2019 07:22
À : armelyonkeu/armel-yonkeu-blog <armel-yonkeu-blog@noreply.github.com>
Cc : Armel YONKEU TCHUIDJANG <Armel.YONKEUTCHUIDJANG@student.umons.ac.be>; Mention <mention@noreply.github.com>
Objet : Re: [armelyonkeu/armel-yonkeu-blog] problèmes avec le blog (#4)


Salut @armelyonkeu<https://github.com/armelyonkeu> ,

Je n'arrive pas à compiler (knit) ton article 1. Il me manque la photo pour cela.
peux tu ajouter la photo manquante dans ton projet et réaliser un commit puis un push

[armel_blog1]<https://user-images.githubusercontent.com/33956170/67923778-22034900-fbaf-11e9-9ced-9300c39dda40.png>

**Comment by armelyonkeu** [comment]
je comprend vraiment pas pourtant j avais bien mis une image

**Comment by armelyonkeu** [comment]
j ai fait le push jai fait le push

**Comment by GuyliannEngels** [comment]
Salut @armelyonkeu ,

la photo que tu souhiates afficher dans ton article se trouve si ton chemin d'accès est le bon dans le dossier Downloads

/home/sv/Downloads/84681ED7-E5C7-4749-AA617380E499D663-790x445.jpg 

Cependant sur GitHub, le dossier sur lequel nous collaborons est armel-yonkey-blog. Tout ce qui ne se trouve pas dans ce dossier sont en local, sur ton ordinateur à toi. Je ne peux donc toujours pas afficher l'image sur mon ordinateur.

Dans ton dossier _posts puis 2019-09-18-article-1, tu dois placer l'image **84681ED7-E5C7-4749-AA617380E499D663-790x445.jpg** dans le dossier images.

**Comment by GuyliannEngels** [comment]
puis faire un commit et un push

**Comment by armelyonkeu** [comment]
D accord je comprend mieux maintenant je le fais toute suite

**Comment by armelyonkeu** [comment]
c est fait

**Comment by GuyliannEngels** [comment]
J'ai enfin pu modifier ton blog

Tu dois lire et comprendre mes modifications. Tiens compte de ces modifications pour tes prochains articles.

- Tu avais modifier le préambule de manière inapproprié 

- Tu n'avais pas mis la photo dans ton projet

- Après avoir placé la photo dans ton projet tu n'as pas respecté le principe des chemins relatifs.

Cela donne plusieurs erreurs sur le même article. Fais plus attention
