### ISSUE TITLE
Table Editor

### ISSUE THREAD

**Issue by armelyonkeu** [armelyonkeu/armel-yonkeu-blog#5]
Bonjour M @GuyliannEngels , je rencontre un soucis avec mon blog. 
En effet l'application Table Editor, permettant de faire un tableau ne fonctionne plus comme avant. Lorsque je l'ouvre aucun tableau n'apparait, je vois juste du blanc comme l'illustre l'image que ve vous ais envoye sur outlook.

**Comment by armelyonkeu** [comment]
ce qui fait que j'ai pas reussi a realiser correctement mon deuxieme tableau de l'article_3

**Comment by GuyliannEngels** [comment]
Bonjour @armelyonkeu ,

Je peux effectivement voir que tu as un souci d'affichage sur ton second tableau. J'y ai apporté une petite correction et le tour était joué.

Je ne sais pas pourquoi ton programme table editor ne fonctionne pas.

Bonne journée 

N'oublie pas de faire un PULL

**Comment by armelyonkeu** [comment]
Merci beaucoup  et bonne journée à vous aussi

Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone
Téléchargez Outlook pour Android<https://aka.ms/ghei36>

________________________________
